- services/inventory-service/src/main/resources/db/migration/V2__core_master_tables.sql
This PR updates the V2 database migration file (`V2__core_master_tables.sql`) to correct the table schema definitions for the core master tables (products, suppliers, and customers). The migration now properly creates all three tables with the correct column definitions and data types.
The original V2 migration had schema issues that were causing Flyway validation errors and preventing the application from starting properly. Since we don't have any production data yet, we modified the existing migration file instead of creating a new one to maintain a clean migration history. This fix ensures the inventory service can start successfully and creates the proper database structure for the inventory management system.
1. **Prerequisites**: Ensure Docker and Docker Compose are running
2. …
> fix(database): update V2 migration with corrected table schema

- shared/api-contracts/openapi/inventory-service-openapi-v1-0_1_2.yaml
This PR standardizes and improves all API endpoint summaries in the OpenAPI specification for better clarity and consistency.
- **Consistency:** Standardize summary patterns across all endpoints
- **Maintainability:** Use general terminology that won't need updates when fields change
- **Clarity:** Ensure all summaries clearly communicate the endpoint's purpose
- **Professional Standards:** Follow industry best practices for API documentation
1. Review the OpenAPI specification changes
2. Verify consistent patterns across all endpoints:
- List endpoints mention "paginated list with optional sorting"
- Create/Update endpoints use "with required fields"
- Get endpoints use "detailed information for specific [entity]"
- Delete endpoints use "permanently remove"
3. Check that summaries are …
> docs(api): improve endpoint summaries for better clarity and consistency

- shared/api-contracts/openapi/inventory-service-openapi-v1-0_1_2.yaml
This PR fixes critical character encoding issues and adds missing business rule documentation to the OpenAPI specification.
- **Encoding Issue:** Turkish characters were corrupted in API documentation
- **Missing Documentation:** Critical business constraint (reorder_point >= safety_stock) was not documented
- **API-Database Alignment:** Ensure API docs match database constraints
1. Verify Turkish characters display correctly as ASCII equivalents
2. Check that reorderPoint descriptions mention the safetyStock constraint
3. Confirm error response example reflects validation rules
4. Validate that API documentation now matches database constraints
- Character encoding: çuval, şişe → cuval, sise
- Business rule documentation added to reorderPoint fields
- Error response example updated for …
> fix(api): resolve Turkish character encoding and document business rules

- docker-compose.yml
- scripts/devdown.bat
- scripts/devdown.sh
- scripts/devup.bat
- scripts/devup.sh
- services/inventory-service/Dockerfile
- services/inventory-service/requests.http
- services/inventory-service/src/main/java/com/petek/inventory_service/controller/ProductController.java
- services/inventory-service/src/main/java/com/petek/inventory_service/dto/ProductRequest.java
- services/inventory-service/src/main/java/com/petek/inventory_service/dto/ProductResponse.java
- services/inventory-service/src/main/java/com/petek/inventory_service/dto/ProductUpdateRequest.java
- services/inventory-service/src/main/java/com/petek/inventory_service/entity/Customer.java
- services/inventory-service/src/main/java/com/petek/inventory_service/entity/Product.java
- services/inventory-service/src/main/java/com/petek/inventory_service/entity/Supplier.java
- services/inventory-service/src/main/java/com/petek/inventory_service/mapper/ProductMapper.java
- services/inventory-service/src/main/java/com/petek/inventory_service/repository/ProductRepository.java
- services/inventory-service/src/main/java/com/petek/inventory_service/service/ProductService.java
- Reorganize folder structure
- Add comments
- Add Dockerfile and update docker-compose.yml
- Add scripts for development
> refactor(inventory-service)

- services/inventory-service/product.http
- services/inventory-service/src/main/java/com/petek/inventory_service/controller/ProductController.java
- services/inventory-service/src/main/java/com/petek/inventory_service/dto/PageInfo.java
- services/inventory-service/src/main/java/com/petek/inventory_service/dto/PageResponse.java
- services/inventory-service/src/main/java/com/petek/inventory_service/dto/ProductFilterRequest.java
- services/inventory-service/src/main/java/com/petek/inventory_service/dto/ProductRequest.java
- services/inventory-service/src/main/java/com/petek/inventory_service/dto/ProductResponse.java
- services/inventory-service/src/main/java/com/petek/inventory_service/dto/ProductUpdateRequest.java
- services/inventory-service/src/main/java/com/petek/inventory_service/repository/ProductRepository.java
- services/inventory-service/src/main/java/com/petek/inventory_service/service/ProductService.java
- services/inventory-service/src/main/java/com/petek/inventory_service/spec/ProductSpecifications.java
- Add filtering to get all products
- Add search to get al products
- Add http status codes for error handling
> feat(product filter search)

- shared/api-contracts/openapi/inventory-service-openapi-v1.yaml
I'll help you create a comprehensive Pull Request description using your team's template from the git-usage.md file. Let me format it properly:
**Pull Request Template for `docs/add-purchasing-promotions-openapi-specs`:**
---
This PR confirms and documents that the OpenAPI specification now includes comprehensive API contracts for V4 (Campaigns & Customer Special Offers) and V5 (Purchase Orders & Purchase Order Items) database migrations. The OpenAPI file contains complete CRUD operations, filtering, sorting, and business rule specifications for all new entities introduced in the recent database migrations.
With the completion of V4 and V5 database migrations, we need corresponding API contracts to enable parallel development. This documentation allows:
- Frontend teams to start building …
> docs(openapi): confirm V4/V5 purchasing & promotions specs are complete

- services/inventory/src/main/java/com/petek/inventoryService/exception/GlobalExceptionHandler.java
- services/inventory/src/main/java/com/petek/inventoryService/exception/OverlapConflictException.java
- services/inventory/src/main/java/com/petek/inventoryService/exception/StateConflictException.java
- services/inventory/src/main/java/com/petek/inventoryService/exception/UnknownQueryParamsException.java
This PR adds a comprehensive global exception handling system to the inventory service, including a `GlobalExceptionHandler` and three custom exception classes that map directly to our OpenAPI `ErrorResponse` schema.
- Provides consistent error responses across all API endpoints
- Implements strict query parameter validation (returns 400 for unknown params)
- Handles business rule violations and time window conflicts
- Maps all Spring validation, constraint, and database errors to our standardized error format
- Essential foundation for implementing the new V4/V5 API endpoints
1. Run the inventory service locally
2. Make a request with an invalid query parameter: `GET /api/v1/products?invalid_param=test`
3. Verify you get a 400 response with `ErrorResponse` format containing …
> feat(exceptions): add GlobalExceptionHandler and custom exceptions

- services/inventory/src/main/java/com/petek/inventoryService/controller/SupplierController.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/SupplierCreateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/SupplierResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/SupplierUpdateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/entity/Supplier.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/SupplierMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/repository/SupplierRepository.java
- services/inventory/src/main/java/com/petek/inventoryService/service/SupplierService.java
- services/inventory/test/supplier.http
- Implemented supplier CRUD operations
> feat(supplier)

- shared/api-contracts/openapi/inventory-service-openapi-v1.yaml
This PR updates the OpenAPI specification to v1.0.0 with comprehensive stock management endpoints and soft delete support. It adds five new stock endpoints, introduces machine-readable error codes, and updates all master data endpoints to support soft delete operations with an `include_deleted` parameter.
- **API Completeness**: Stock management is core functionality requiring well-documented REST endpoints
- **Version Maturity**: Upgrading to v1.0.0 signals API stability for production use
- **Error Handling**: Machine-readable error codes enable better frontend error handling and user experience
- **Soft Delete Support**: API consumers need to control visibility of deleted records for different use cases
- **Developer Experience**: Comprehensive examples and clear conflict scenarios …
> feat(api): update OpenAPI v1.0.0 with stock endpoints and soft delete

- services/inventory/src/main/java/com/petek/inventoryService/dto/CustomerCreateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/CustomerResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/CustomerUpdateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/PageResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/ProductCreateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/ProductFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/ProductResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/ProductUpdateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/SupplierCreateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/SupplierResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/SupplierUpdateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/entity/Customer.java
- services/inventory/src/main/java/com/petek/inventoryService/entity/CustomerSegment.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/CustomerMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/ProductMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/SupplierMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/service/CustomerService.java
- services/inventory/src/main/java/com/petek/inventoryService/service/ProductService.java
- services/inventory/src/main/java/com/petek/inventoryService/service/SupplierService.java
- services/inventory/src/main/java/com/petek/inventoryService/spec/ProductSpecifications.java
- Update DTOS to use Class
- Change CustomerSegmen Enum location
> refactor(dto)

- services/inventory/src/main/java/com/petek/inventoryService/dto/ErrorResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/exception/GlobalExceptionHandler.java
- Improve error handling and response structure
- Remove redundant exception handler
- Improve exception handling
> refactor(exception)

- services/inventory/src/main/java/com/petek/inventoryService/controller/ProductController.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/ProductItemResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/ProductResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/entity/Product.java
- services/inventory/src/main/java/com/petek/inventoryService/entity/ProductSupplier.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/ProductMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/ProductSupplierMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/service/ProductService.java
- services/inventory/src/main/java/com/petek/inventoryService/service/ProductSupplierService.java
- services/inventory/src/main/java/com/petek/inventoryService/service/SupplierService.java
- Add activeSuppliers to ProductResponse
- Add preferedSupplier to ProductResponse
- Add ProductItemResponse for Get All Products
> refactor(get products)

- services/inventory/src/main/java/com/petek/inventoryService/controller/ProductController.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/product/ProductCreateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/product/ProductFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/product/ProductItemResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/product/ProductResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/product/ProductUpdateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/productSupplier/ProductGetSuppliersFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/productSupplier/ProductSupplierItemResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/ProductMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/ProductSupplierMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/service/ProductService.java
- services/inventory/src/main/java/com/petek/inventoryService/service/ProductSupplierService.java
- services/inventory/src/main/java/com/petek/inventoryService/spec/ProductSpecifications.java
- services/inventory/src/main/java/com/petek/inventoryService/spec/ProductSupplierSpecifications.java
- services/inventory/test/product.http
- Change dto's folders
- Add utils
- Refactor exception types
- Implemented get all suppliers for product
> refactor(product)

- services/inventory/src/main/java/com/petek/inventoryService/controller/CustomerController.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/customer/CustomerCreateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/customer/CustomerFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/customer/CustomerResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/customer/CustomerUpdateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/CustomerMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/repository/CustomerRepository.java
- services/inventory/src/main/java/com/petek/inventoryService/service/CustomerService.java
- services/inventory/src/main/java/com/petek/inventoryService/spec/CustomerSpecifications.java
- services/inventory/test/customer.http
- Change DTO's folder
- Refactor CustomerService exceptions
- Add updateAt to CustomerResponse
- Implemented get all customers with filters and sort
> refactor(customers)

- services/frontend/angular.json
- services/frontend/package-lock.json
- services/frontend/package.json
- services/frontend/tsconfig.app.json
- services/frontend/tsconfig.json
- services/frontend/tsconfig.spec.json
- Added angular.json for Angular workspace configuration
- Added tsconfig.app.json, tsconfig.spec.json, and tsconfig.json for TypeScript
- Added package-lock.json to lock dependencies
- Ensured configs are tracked and no longer excluded by .gitignore
> chore(config): add missing Angular and TypeScript config files

- services/frontend/src/app/app.routes.ts
- services/frontend/src/app/customers/customer-editor/customer-editor.html
- services/frontend/src/app/customers/customer-editor/customer-editor.scss
- services/frontend/src/app/customers/customer-editor/customer-editor.spec.ts
- services/frontend/src/app/customers/customer-editor/customer-editor.ts
- services/frontend/src/app/customers/customer-listing/customer-listing.html
- services/frontend/src/app/customers/customer-listing/customer-listing.scss
- services/frontend/src/app/customers/customer-listing/customer-listing.spec.ts
- services/frontend/src/app/customers/customer-listing/customer-listing.ts
- services/frontend/src/app/customers/customer/customer.html
- services/frontend/src/app/customers/customer/customer.scss
- services/frontend/src/app/customers/customer/customer.spec.ts
- services/frontend/src/app/customers/customer/customer.ts
- services/frontend/src/app/models/customer.model.ts
- services/frontend/src/app/pages/customer-page/customer-page.html
- services/frontend/src/app/pages/customer-page/customer-page.scss
- services/frontend/src/app/pages/customer-page/customer-page.spec.ts
- services/frontend/src/app/pages/customer-page/customer-page.ts
- services/frontend/src/app/pages/mock-data.service.ts
- services/frontend/src/app/shared/header/header.html
- services/frontend/src/app/shared/header/header.scss
- services/frontend/src/app/shared/header/header.ts
- CustomerPage container and /customers route
- CustomerListing table with search, status filters, and delete actions
- CustomerEditor modal for add/edit customer records
- Single customer component for row/details view
- Extended MockDataService with customer CRUD operations
- Added Customer model
> feat(ui): add customer page with listing, editor, filters, and CRUD

- services/inventory/src/main/java/com/petek/inventoryService/controller/CurrentStockController.java
- services/inventory/src/main/java/com/petek/inventoryService/controller/ProductController.java
- services/inventory/src/main/java/com/petek/inventoryService/controller/StockMovementController.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/stock/CurrentStockFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/stock/CurrentStockResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/stock/StockMovementCreateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/stock/StockMovementFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/stock/StockMovementResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/entity/CurrentStock.java
- services/inventory/src/main/java/com/petek/inventoryService/entity/Product.java
- services/inventory/src/main/java/com/petek/inventoryService/entity/StockMovement.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/CurrentStockMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/StockMovementMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/repository/CurrentStockRepository.java
- services/inventory/src/main/java/com/petek/inventoryService/repository/StockMovementRepository.java
- services/inventory/src/main/java/com/petek/inventoryService/service/CurrentStockService.java
- services/inventory/src/main/java/com/petek/inventoryService/service/StockMovementService.java
- services/inventory/src/main/java/com/petek/inventoryService/spec/CurrentStockSpecifications.java
- services/inventory/src/main/java/com/petek/inventoryService/spec/StockMovementSpecifications.java
- services/inventory/test/currentStock.http
- services/inventory/test/product.http
- services/inventory/test/stockMovement.http
- Implemented Create Stock
- Implemented Get All Stock Movement with Filters and Sort
- Implemented Get All Stock Movement of a Product
- Implemented Get All Current Stock with Filters and Sort
- Implemented Get Current Stock of Product
> feat(stock)

- services/inventory/src/main/java/com/petek/inventoryService/config/WebConfig.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/customer/CustomerFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/product/ProductFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/product/ProductGetSuppliersFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/productSupplier/ProductSupplierFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/supplier/SupplierFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/supplier/SupplierGetProductsFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/entity/Product.java
- services/inventory/src/main/java/com/petek/inventoryService/entity/Supplier.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/CurrentStockMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/ProductMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/StockMovementMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/service/CurrentStockService.java
- services/inventory/src/main/java/com/petek/inventoryService/service/CustomerService.java
- services/inventory/src/main/java/com/petek/inventoryService/service/ProductService.java
- services/inventory/src/main/java/com/petek/inventoryService/service/ProductSupplierService.java
- services/inventory/src/main/java/com/petek/inventoryService/service/StockMovementService.java
- services/inventory/src/main/java/com/petek/inventoryService/service/SupplierService.java
- services/inventory/test/productSupplier.http
- Refactor dto filter request
- Add one to many in prodcut and supplier
- Refactor mappers
- Refactor services
- Implemented return available quantity 
- Implemented WebConfig for CORS
> refactor(project)

- services/inventory/src/main/java/com/petek/inventoryService/controller/PurchaseOrderController.java
- services/inventory/src/main/java/com/petek/inventoryService/controller/PurchaseOrderItemController.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/purchaseOrder/PurchaseOrderCreateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/purchaseOrder/PurchaseOrderFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/purchaseOrder/PurchaseOrderResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/purchaseOrder/PurchaseOrderUpdateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/purchaseOrderItem/PurchaseOrderItemCreateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/purchaseOrderItem/PurchaseOrderItemFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/purchaseOrderItem/PurchaseOrderItemResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/purchaseOrderItem/PurchaseOrderItemUpdateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/entity/PurchaseOrder.java
- services/inventory/src/main/java/com/petek/inventoryService/entity/PurchaseOrderItem.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/ProductMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/PurchaseOrderItemMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/PurchaseOrderMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/repository/PurchaseOrderItemRepository.java
- services/inventory/src/main/java/com/petek/inventoryService/repository/PurchaseOrderRepository.java
- services/inventory/src/main/java/com/petek/inventoryService/service/ProductService.java
- services/inventory/src/main/java/com/petek/inventoryService/service/PurchaseOrderItemService.java
- services/inventory/src/main/java/com/petek/inventoryService/service/PurchaseOrderService.java
- services/inventory/src/main/java/com/petek/inventoryService/spec/PurchaseOrderSpecifications.java
- services/inventory/test/purchaseOrder.http
- services/inventory/test/purchaseOrderItem.http
This PR implements comprehensive purchase order management functionality with full CRUD operations for both purchase orders and purchase order items.
- Implemented Create Purchase Order
- Implemented Get Purchase Order by ID
- Implemented Update Purchase Order
- Implemented Delete Purchase Order
- Implemented Get All Purchase Orders with Filter, Sort and Pagination
- Implemented Create Purchase Order Item
- Implemented Get Purchase Order Item by ID
- Implemented Update Purchase Order Item
- Implemented Delete Purchase Order Item
- Implemented Get All Purchase Order Items for Given Purchase Order ID
> feat(purchase)

- services/inventory/src/main/java/com/petek/inventoryService/controller/SalesOrderController.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/saleOrder/SalesOrderCreateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/saleOrder/SalesOrderResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/salesOrder/SalesOrderCreateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/salesOrder/SalesOrderFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/salesOrder/SalesOrderItemCreateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/salesOrder/SalesOrderItemFilterRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/salesOrder/SalesOrderItemResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/salesOrder/SalesOrderItemUpdateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/salesOrder/SalesOrderResponse.java
- services/inventory/src/main/java/com/petek/inventoryService/dto/salesOrder/SalesOrderUpdateRequest.java
- services/inventory/src/main/java/com/petek/inventoryService/entity/SalesOrder.java
- services/inventory/src/main/java/com/petek/inventoryService/entity/SalesOrderItem.java
- services/inventory/src/main/java/com/petek/inventoryService/mapper/SalesOrderMapper.java
- services/inventory/src/main/java/com/petek/inventoryService/repository/CampaignRepository.java
- services/inventory/src/main/java/com/petek/inventoryService/repository/CustomerSpecialOfferRepository.java
- services/inventory/src/main/java/com/petek/inventoryService/repository/SalesOrderItemRepository.java
- services/inventory/src/main/java/com/petek/inventoryService/repository/SalesOrderRepository.java
- services/inventory/src/main/java/com/petek/inventoryService/service/SalesOrderItemService.java
- services/inventory/src/main/java/com/petek/inventoryService/service/SalesOrderService.java
- services/inventory/src/main/java/com/petek/inventoryService/spec/SalesOrderSpecifications.java
- services/inventory/test/campaign.http
- services/inventory/test/salesOrder.http
This PR implements comprehensive sales order management functionality with full CRUD operations, advanced filtering, sorting, and pagination capabilities.
- Implemented complete CRUD operations for sales orders
- Added create sales order functionality for new order creation
- Enhanced order management capabilities across the system
- Implemented complete CRUD operations for sales order items
- Added create sales order items functionality with comprehensive validations
- Enhanced item-level management and tracking capabilities
- Implemented get all sales orders with advanced filtering options
- Added comprehensive sorting capabilities for better data organization
- Integrated pagination support for efficient data handling and performance
- Implemented get all sales order items with sorting …
> feat(sales)

- services/inventory/src/main/java/com/petek/inventoryService/service/ProductSupplierService.java
- services/inventory/test/supplier.http
Fixed bugs where API would fail when querying non-existent product or supplier IDs.
- Fix listing suppliers when product ID doesn't exist
- Fix listing products when supplier ID doesn't exist
- Added proper error handling for missing resources
> refactor(product supplier)

- services/frontend/src/app/pages/supplier-page/supplier-page.html
- services/frontend/src/app/pages/supplier-page/supplier-page.ts
- services/frontend/src/app/pages/supplier.service.ts
- services/frontend/src/app/products/product-editor/product-editor.html
- services/frontend/src/app/products/product-editor/product-editor.ts
- services/frontend/src/app/suppliers/supplier-editor/supplier-editor.html
- services/frontend/src/app/suppliers/supplier-editor/supplier-editor.scss
- services/frontend/src/app/suppliers/supplier-editor/supplier-editor.ts
- Implements POST request functionality for suppliers (create, edit, delete)
- Updates supplier editor (ID field set to readonly)
- Adds UI improvements for supplier management
- Enables supplier CRUD operations through the API
- Protects critical fields from being modified
- Improves consistency with product CRUD features
> feat(supplier): implement POST requests

- services/frontend/src/app/products/sales-chart/sales-chart.html
- services/frontend/src/app/products/sales-chart/sales-chart.scss
- services/frontend/src/app/products/sales-chart/sales-chart.ts
- Refactors the product sales chart component
- Cleans up HTML, SCSS, and TS files for better readability
- Improves component structure and separation of concerns
- Simplifies styles for maintainability
- Reduces technical debt and makes the sales chart easier to maintain
- Prepares the component for future enhancements (e.g., more chart types or data sources)
- Aligns with coding and styling conventions across the project
> refactor(product): improve sales chart component structure and styles
